### ISSUE TITLE
Cross-Posting Issue From cal_engine

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#4]
When I use the cqf-ruler as terminology provider and evaluate the col-logic against two encounters I get this result:

```
ValueSet 2.16.840.1.113883.3.464.1003.108.11.1001 does not contain 'http://snomed.info/sct' 285312008
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://snomed.info/sct' 415527002
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://snomed.info/sct' 415527002
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 contains 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 contains 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://snomed.info/sct' 415527002
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3
2017-07-21 12:22:58 INFO  FhirContext:172 - Creating new FHIR context for FHIR version [DSTU3]

```

When I copy the JpaTerminologyProvider code into a LocalFhirTerminologyProvider that loads the downloaded valueSets into a Map and run the same test, I get:

```
ValueSet 2.16.840.1.113883.3.464.1003.108.11.1001 contains 'http://snomed.info/sct' 285312008
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://snomed.info/sct' 415527002
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 contains 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://snomed.info/sct' 415527002
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 contains 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 contains 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://snomed.info/sct' 415527002
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3
2017-07-21 12:28:01 INFO  FhirContext:172 - Creating new FHIR context for FHIR version [DSTU3]

```

From this I conclude that there's different behavior in Jpa's `ValueSet vs = valueSetProvider.getDao().read(new IdType(valueSet.getId()));` and my local 'ValueSet vs = valueSets.get(valueSet.getId());'

**Comment by c-schuler** [comment]
Hmmm. This is odd behavior indeed.

I ran some simple validations via an HTTP Client like the following:
GET http://measure.eval.kanvix.com/cqf-ruler/baseDstu3//ValueSet/2.16.840.1.113883.3.464.1003.108.11.1001/$validate-code?system=http://snomed.info/sct&code=285312008

These are returning "Code not found" even though they are obviously present in the ValueSet. So, it doesn't look like the JpaTerminologyProvider code is the culprit here. 

It appears as though the $expand operation may be the issue as it looks like it is returning an empty expansion when the following is run:
GET http://measure.eval.kanvix.com/cqf-ruler/baseDstu3/ValueSet/2.16.840.1.113883.3.464.1003.108.11.1001/$expand

I will continue investigating and keep you posted.

**Comment by c-schuler** [comment]
Resolved...
This was a programmer error. Get the latest.
See results of operation here:
http://measure.eval.kanvix.com/cqf-ruler/baseDstu3/Measure/col/$evaluate?patient=Patient-12214&startPeriod=2014-01-01&endPeriod=2014-12-31

**Comment by jeffeastman** [comment]
Still not 100% by my test. Still not finding the Colon cancer in `Value Set 2.16.840.1.113883.3.464.1003.108.11.1001,` the Colectomy in `ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019` or the Sigmoidoscopy in `ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010`.

HAPI as Terminology Server
```
ValueSet 2.16.840.1.113883.3.464.1003.108.11.1001 does not contain 'http://snomed.info/sct' 285312008
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 does not contain 'http://www.ama-assn.org/go/cpt' 44155
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://www.ama-assn.org/go/cpt' 44155
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://www.ama-assn.org/go/cpt' 45331
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://www.ama-assn.org/go/cpt' 44155
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 contains 'http://www.ama-assn.org/go/cpt' 45331
Adding resource - Observation-10
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 contains 'http://loinc.org' 2335-8
Adding resource - Procedure-4
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://www.ama-assn.org/go/cpt' 44155
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 contains 'http://loinc.org' 14563-1
Adding resource - Observation-5
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://www.ama-assn.org/go/cpt' 45331
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3

```
Local Terminology Server

```
ValueSet 2.16.840.1.113883.3.464.1003.108.11.1001 contains 'http://snomed.info/sct' 285312008
Adding resource - Condition-1
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1019 contains 'http://www.ama-assn.org/go/cpt' 44155
Adding resource - Procedure-14
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://www.ama-assn.org/go/cpt' 44155
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://www.ama-assn.org/go/cpt' 45331
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.108.12.1020 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 2335-8
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 contains 'http://snomed.info/sct' 44441009
Adding resource - Procedure-9
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://www.ama-assn.org/go/cpt' 44155
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 14563-1
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 contains 'http://www.ama-assn.org/go/cpt' 45331
Adding resource - Observation-10
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1010 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 contains 'http://loinc.org' 2335-8
Adding resource - Procedure-4
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://snomed.info/sct' 44441009
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://www.ama-assn.org/go/cpt' 44155
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 contains 'http://loinc.org' 14563-1
Adding resource - Observation-5
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://www.ama-assn.org/go/cpt' 45331
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3
ValueSet 2.16.840.1.113883.3.464.1003.198.12.1011 does not contain 'http://loinc.org' 8716-3

```

**Comment by jeffeastman** [comment]
Should be reopened. I still have two more issues that I posted on the thread. I need to figure out how to get my test case to you.

Jeff
